//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChryslerScanner.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChryslerScanner.Languages.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS tools.
        /// </summary>
        public static string ABSTools {
            get {
                return ResourceManager.GetString("ABSTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery voltage.
        /// </summary>
        public static string BatteryVoltage {
            get {
                return ResourceManager.GetString("BatteryVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink duration:.
        /// </summary>
        public static string BlinkDuration {
            get {
                return ResourceManager.GetString("BlinkDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrap tools.
        /// </summary>
        public static string BootstrapTools {
            get {
                return ResourceManager.GetString("BootstrapTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate checksum.
        /// </summary>
        public static string CalculateChecksum {
            get {
                return ResourceManager.GetString("CalculateChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate CRC.
        /// </summary>
        public static string CalculateCRC {
            get {
                return ResourceManager.GetString("CalculateCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCD-bus on demand.
        /// </summary>
        public static string CCDBusOnDemand {
            get {
                return ResourceManager.GetString("CCDBusOnDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCD-bus termination / bias.
        /// </summary>
        public static string CCDBusTerminationBias {
            get {
                return ResourceManager.GetString("CCDBusTerminationBias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCD-bus transceiver.
        /// </summary>
        public static string CCDBusTransceiver {
            get {
                return ResourceManager.GetString("CCDBusTransceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy table to clipboard.
        /// </summary>
        public static string CopyTableToClipboard {
            get {
                return ResourceManager.GetString("CopyTableToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string Diagnostics {
            get {
                return ResourceManager.GetString("Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        public static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine tools.
        /// </summary>
        public static string EngineTools {
            get {
                return ResourceManager.GetString("EngineTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand &gt;&gt;.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handshake.
        /// </summary>
        public static string Handshake {
            get {
                return ResourceManager.GetString("Handshake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat interval:.
        /// </summary>
        public static string HeartbeatInterval {
            get {
                return ResourceManager.GetString("HeartbeatInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial.
        /// </summary>
        public static string Imperial {
            get {
                return ResourceManager.GetString("Imperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include timestamp in log files.
        /// </summary>
        public static string IncludeTimestampInLogFiles {
            get {
                return ResourceManager.GetString("IncludeTimestampInLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main:.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        public static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        public static string Metric {
            get {
                return ResourceManager.GetString("Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGCDebug.
        /// </summary>
        public static string NGCDebug {
            get {
                return ResourceManager.GetString("NGCDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBD config.
        /// </summary>
        public static string OBDConfig {
            get {
                return ResourceManager.GetString("OBDConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite duplicate ID.
        /// </summary>
        public static string OverwriteDuplicateID {
            get {
                return ResourceManager.GetString("OverwriteDuplicateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCI-bus on demand.
        /// </summary>
        public static string PCIBusOnDemand {
            get {
                return ResourceManager.GetString("PCIBusOnDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCI-bus transceiver.
        /// </summary>
        public static string PCIBusTransceiver {
            get {
                return ResourceManager.GetString("PCIBusTransceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read memory.
        /// </summary>
        public static string ReadMemory {
            get {
                return ResourceManager.GetString("ReadMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read/Write memory.
        /// </summary>
        public static string ReadWriteMemory {
            get {
                return ResourceManager.GetString("ReadWriteMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat interval.
        /// </summary>
        public static string RepeatInterval {
            get {
                return ResourceManager.GetString("RepeatInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request:.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset view.
        /// </summary>
        public static string ResetView {
            get {
                return ResourceManager.GetString("ResetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBEC2Logic.
        /// </summary>
        public static string SBEC2Logic {
            get {
                return ResourceManager.GetString("SBEC2Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCI-bus (Engine).
        /// </summary>
        public static string SCIBusEngine {
            get {
                return ResourceManager.GetString("SCIBusEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCI-bus (Transmission).
        /// </summary>
        public static string SCIBusTransmission {
            get {
                return ResourceManager.GetString("SCIBusTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message(s).
        /// </summary>
        public static string SendMessages {
            get {
                return ResourceManager.GetString("SendMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send packet.
        /// </summary>
        public static string SendPacket {
            get {
                return ResourceManager.GetString("SendPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send random messages.
        /// </summary>
        public static string SendRandomMessages {
            get {
                return ResourceManager.GetString("SendRandomMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set LEDs.
        /// </summary>
        public static string SetLEDs {
            get {
                return ResourceManager.GetString("SetLEDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings:.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort messages by ID byte.
        /// </summary>
        public static string SortMessagesByIDByte {
            get {
                return ResourceManager.GetString("SortMessagesByIDByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop repeated message(s).
        /// </summary>
        public static string StopRepeatedMessages {
            get {
                return ResourceManager.GetString("StopRepeatedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        public static string Transmission {
            get {
                return ResourceManager.GetString("Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB communication.
        /// </summary>
        public static string USBCommunication {
            get {
                return ResourceManager.GetString("USBCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version info.
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
    }
}
